// Sources RSS et APIs officielles — seed initial
export const INITIAL_SOURCES = [
  // === GOUVERNEMENT CANADA ===
  {
    name: "Canada.ca — Nouvelles",
    url: "https://www.canada.ca/fr",
    rssUrl: "https://www.canada.ca/content/dam/canada/rss/nouvelles.xml",
    type: "rss",
    province: "federal",
    defaultCategory: "gouvernement-federal",
  },
  {
    name: "IRCC — Immigration Canada",
    url: "https://www.canada.ca/fr/immigration-refugies-citoyennete.html",
    rssUrl: "https://www.canada.ca/content/dam/ircc/rss/nouvelles.xml",
    type: "rss",
    province: "federal",
    defaultCategory: "immigration-canada",
  },
  {
    name: "Statistique Canada",
    url: "https://www.statcan.gc.ca",
    rssUrl: "https://www.statcan.gc.ca/en/sc/rss/daily.xml",
    type: "rss",
    province: "federal",
    defaultCategory: "economie",
  },
  {
    name: "Banque du Canada",
    url: "https://www.banqueducanada.ca",
    rssUrl: "https://www.banqueducanada.ca/feed/",
    type: "rss",
    province: "federal",
    defaultCategory: "taux-interet",
  },
  // === NOUVEAU-BRUNSWICK ===
  {
    name: "Gouvernement du Nouveau-Brunswick",
    url: "https://www2.gnb.ca",
    rssUrl: "https://www2.gnb.ca/content/gnb/fr/nouvelles.rss.html",
    type: "rss",
    province: "NB",
    defaultCategory: "gouvernement-nb",
  },
  {
    name: "Immigration Nouveau-Brunswick",
    url: "https://www.immigrer.com/categories/nouveau-brunswick/",
    rssUrl: "https://www.immigrer.com/categories/nouveau-brunswick/feed/",
    type: "rss",
    province: "NB",
    defaultCategory: "immigration-nb",
  },
  {
    name: "Ville de Moncton",
    url: "https://www.moncton.ca",
    rssUrl: "https://www.moncton.ca/fr/nouvelles.rss",
    type: "rss",
    province: "NB",
    defaultCategory: "moncton",
  },
  {
    name: "Ville de Fredericton",
    url: "https://www.fredericton.ca",
    rssUrl: "https://www.fredericton.ca/en/news.rss",
    type: "rss",
    province: "NB",
    defaultCategory: "fredericton",
  },
  // === MÉDIAS ===
  {
    name: "Radio-Canada NB",
    url: "https://ici.radio-canada.ca/nouvelle/regional/regions/atlantique/nouveau-brunswick",
    rssUrl: "https://ici.radio-canada.ca/rss/6307",
    type: "rss",
    province: "NB",
    defaultCategory: "actualites-nb",
  },
  {
    name: "Radio-Canada Canada",
    url: "https://ici.radio-canada.ca",
    rssUrl: "https://ici.radio-canada.ca/rss/4159",
    type: "rss",
    province: "federal",
    defaultCategory: "politique-federale",
  },
  {
    name: "CBC New Brunswick",
    url: "https://www.cbc.ca/cmlink/rss-canada-newbrunswick",
    rssUrl: "https://www.cbc.ca/cmlink/rss-canada-newbrunswick",
    type: "rss",
    province: "NB",
    defaultCategory: "actualites-nb",
  },
  {
    name: "CBC Canada",
    url: "https://www.cbc.ca",
    rssUrl: "https://www.cbc.ca/cmlink/rss-canada",
    type: "rss",
    province: "federal",
    defaultCategory: "politique-federale",
  },
  {
    name: "Le Devoir — Canada",
    url: "https://www.ledevoir.com",
    rssUrl: "https://www.ledevoir.com/rss/la-une.xml",
    type: "rss",
    province: "federal",
    defaultCategory: "actualites",
  },
  {
    name: "Immigrer.com",
    url: "https://www.immigrer.com",
    rssUrl: "https://www.immigrer.com/feed/",
    type: "rss",
    province: "federal",
    defaultCategory: "immigration-canada",
  },
]

export const CATEGORIES = [
  // Nouveau-Brunswick
  { slug: "gouvernement-nb", name: "Gouvernement NB", province: "NB", priority: 90 },
  { slug: "politique-nb", name: "Politique NB", province: "NB", priority: 88 },
  { slug: "immigration-nb", name: "Immigration NB", province: "NB", priority: 95 },
  { slug: "nbpnp", name: "Programme Candidats NB", province: "NB", priority: 92 },
  { slug: "emploi-nb", name: "Emploi NB", province: "NB", priority: 85 },
  { slug: "logement-nb", name: "Logement NB", province: "NB", priority: 82 },
  { slug: "sante-nb", name: "Santé NB", province: "NB", priority: 78 },
  { slug: "education-nb", name: "Éducation NB", province: "NB", priority: 75 },
  { slug: "economie-nb", name: "Économie NB", province: "NB", priority: 80 },
  { slug: "moncton", name: "Moncton", province: "NB", priority: 70 },
  { slug: "dieppe", name: "Dieppe", province: "NB", priority: 68 },
  { slug: "fredericton", name: "Fredericton", province: "NB", priority: 68 },
  { slug: "saint-john", name: "Saint John", province: "NB", priority: 65 },
  { slug: "edmundston", name: "Edmundston", province: "NB", priority: 63 },
  { slug: "actualites-nb", name: "Actualités NB", province: "NB", priority: 72 },
  // Canada fédéral
  { slug: "gouvernement-federal", name: "Gouvernement fédéral", province: "federal", priority: 85 },
  { slug: "politique-federale", name: "Politique fédérale", province: "federal", priority: 83 },
  { slug: "immigration-canada", name: "Immigration Canada", province: "federal", priority: 90 },
  { slug: "entree-express", name: "Entrée express", province: "federal", priority: 92 },
  { slug: "francophonie", name: "Francophonie", province: "federal", priority: 88 },
  { slug: "residence-permanente", name: "Résidence permanente", province: "federal", priority: 88 },
  { slug: "permis-travail", name: "Permis de travail", province: "federal", priority: 85 },
  { slug: "permis-etudes", name: "Permis d'études", province: "federal", priority: 82 },
  { slug: "citoyennete", name: "Citoyenneté", province: "federal", priority: 80 },
  { slug: "economie", name: "Économie", province: "federal", priority: 80 },
  { slug: "emploi", name: "Emploi", province: "federal", priority: 78 },
  { slug: "logement", name: "Logement", province: "federal", priority: 78 },
  { slug: "sante", name: "Santé", province: "federal", priority: 75 },
  { slug: "taux-interet", name: "Taux d'intérêt", province: "federal", priority: 82 },
  { slug: "inflation", name: "Inflation", province: "federal", priority: 80 },
  { slug: "fiscalite", name: "Fiscalité", province: "federal", priority: 75 },
  { slug: "actualites", name: "Actualités Canada", province: "federal", priority: 60 },
]
